---
# task/prerequisites file for manage_netplan
- name: "Install required roles"
  ansible.builtin.command:
    cmd: "ansible-galaxy install {{ item }}"
  loop: "{{ manage_netplan_prerequisites_roles }}"
  changed_when: false
  delegate_to: localhost
  run_once: true
